name: Docker

on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest

    env:
      image_name: princemaple/docker-caddy

    strategy:
      matrix:
        dns:
          - acmedns
          - cloudflare
          - route53
          - duckdns
          - dnspod
          - alidns
          - digitalocean
          - hetzner
          - vultr
          - azure
          - gandi
          - openstack-designate
          - googleclouddns
          - godaddy
          - netcup
          - metaname
          - netlify
          - ovh
          - vercel
          - loopia
          - dinahosting
          - glesys
          - dynv6
          - ionos
          - civo
          - scaleway
          - porkbun
          - inwx
          - hosttech
          - directadmin

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push latest
        uses: docker/build-push-action@v5
        if: matrix.dns == 'cloudflare'
        with:
          context: .
          push: true
          tags: ${{ env.image_name }}:latest
          build-args: DNS=cloudflare

      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.image_name }}:${{ github.event.release.tag_name }}-${{ matrix.dns }}
          build-args: |
            DNS=${{ matrix.dns }}
