name: Docker

on:
  release:
    types: [published]

env:
  IMAGE_NAME: princemaple/docker-caddy

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dns:
          - cloudflare
          - route53
          - duckdns
          - lego-deprecated
          - dnspod
          - alidns
          - digitalocean
          - hetzner
          - vultr
          - azure
          - gandi
          - openstack-designate
          - googleclouddns
          - godaddy
          - netcup
          - metaname
          - netlify

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: docker build . --file Dockerfile --arg DNS=${{ matrix.dns }} --tag $IMAGE_NAME:${{ matrix.dns }}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push latest
        uses: docker/build-push-action@v3
        if: matrix.dns == 'cloudflare'
        with:
          context: .
          push: true
          tags: $IMAGE_NAME:latest

      - name: Build and push tag
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: $IMAGE_NAME:${{ github.event.release.tag_name }}-${{ matrix.dns }}
